package com.myspace.shipping_quote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shipment implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Shipment() {
    }




}